-- DROP TABLES IF THEY EXIST ALREADY
DROP TABLE IF EXISTS TableInSection;
DROP TABLE IF EXISTS TableSetInSection;
DROP TABLE IF EXISTS TableInTableSet;
DROP TABLE IF EXISTS SectionInLayout;

DROP TABLE IF EXISTS Layout;
DROP TABLE IF EXISTS Section;

DROP TABLE IF EXISTS Reservation;
DROP TABLE IF EXISTS Customer;

DROP TABLE IF EXISTS TableSet;
DROP TABLE IF EXISTS _Table;
DROP TABLE IF EXISTS "Table";